#!/usr/bin/env bash
# Sync the dev schema (SQLite) from the production schema (PostgreSQL).
# Run this whenever you add a new model to prisma/schema.prisma.
#
# This script:
#   1. Reads prisma/schema.prisma
#   2. Replaces the datasource block with SQLite
#   3. Writes prisma/schema.dev.prisma
#   4. Regenerates the Prisma client for SQLite

set -e
cd "$(dirname "$0")/.."

python3 << 'PYEOF'
import re
with open('prisma/schema.prisma') as f:
    prod = f.read()
match = re.search(r'datasource db \{[^}]*\}', prod)
if not match:
    raise SystemExit('Could not find datasource block')
end = match.end()
rest = prod[end:]
dev = '''// DEVELOPMENT schema — SQLite variant for local development.
// The production schema is prisma/schema.prisma (PostgreSQL).
// This file is AUTO-GENERATED by scripts/sync-dev-schema.sh — DO NOT EDIT.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
''' + rest
with open('prisma/schema.dev.prisma', 'w') as f:
    f.write(dev)
print('✓ Generated prisma/schema.dev.prisma (25 models, SQLite)')
PYEOF

echo "✓ Regenerating Prisma client for SQLite..."
bunx prisma generate --schema=prisma/schema.dev.prisma
echo "✓ Done"
